language: ruby
install:
  - sudo apt-get update
  - sudo apt-get install gnuplot
  - gnuplot -e "set terminal" < /dev/null 2>&1
  - bundle install
  - go_version="1.14.1"
  - wget http://golang.org/dl/go${go_version}.linux-amd64.tar.gz
  - sudo tar -C /usr/local -xzf go${go_version}.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - export GOPATH="$HOME/go"
  - export PATH="$PATH:$GOPATH/bin"
  - mkdir -p "$HOME/go/{src,pkg,bin}"
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
script:
  - rake go_get
  - rake spec
  - rake test_core
notifications:
  slack:
    secure: fH8tRyxWHL60OV6QuJlzig9lCLbjfpHx8E6D2EzgQz7+/wqAxtoTUyiN7mbpEJa4hyQeZfpmMpDTnl2tHD6eI8yqjAsY4Q+jt21tCKyrKMegq9Pypd4eMP4o+DupT2mXm0K3cZ2Kgb+yP8AuJPoTy20j3kpmnDFWdqRnhgpBLC8=
