
language: ruby
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install libglib2.0-dev autotools-dev golang
  - sudo go get -u github.com/hayamiz/perfmonger/core/subsystem
  - sudo go get -u golang.org/x/crypto/ssh/terminal
  - bundle install
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
script:
  - rake spec
  - rake test_core
