
language: ruby
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install libglib2.0-dev autotools-dev golang
  - bundle install
rvm:
  - 1.8.7
  - 1.9.3
script:
  - rake spec
  - rake test_core
