#!/bin/bash

cd $(cd $(dirname $0); pwd)

source ../00_LOAD_GO_DEVENV.sh

if [[ $1 = "-" ]]; then
    # do self build
    case `uname -s` in
        (Linux)
            os="linux"
            ;;
        (Darwin)
            os="darwin"
            ;;
        (*)
            os=""
            ;;
    esac
    case `uname -m` in
        (x86_64|amd64)
            arch="amd64"
            ;;
        (*)
            arch=""
            ;;
    esac

    TARGET=("${os} ${arch}")
else
    # cross build
    TARGET=("linux amd64")
fi

set -e

GO_DEPS=$(ls internal/perfmonger/*.go)

makefile=`mktemp`

cat <<EOF > $makefile
# DO NOT EDIT MANUALLY
# generated by build.sh

GO_DEPS := $(echo ${GO_DEPS})

GOPATH := ${GOPATH}
GOROOT := ${GOROOT}

.PHONY: all build clean

all: build

EOF

TARGETS=()

for idx in $(seq 0 $((${#TARGET[@]}-1))); do
    set -- ${TARGET[$idx]}
    export var_GOOS=$1
    export var_GOARCH=$2

    # Build single perfmonger-core binary
    TARGETS+=(../lib/exec/perfmonger-core_${var_GOOS}_${var_GOARCH})

    cat <<EOF >> $makefile

../lib/exec/perfmonger-core_${var_GOOS}_${var_GOARCH}: cmd/perfmonger-core/perfmonger-core.go \$(GO_DEPS)
	cd cmd/perfmonger-core && GOOS=${var_GOOS} GOARCH=${var_GOARCH} go build -o \$@ perfmonger-core.go

EOF

done

cat <<EOF >> $makefile

build: ${TARGETS[*]}

clean:
	rm -f ${TARGETS[*]}

EOF

mv $makefile ./Makefile

make

# Create compatibility wrappers
echo "Creating compatibility wrappers..."
for idx in $(seq 0 $((${#TARGET[@]}-1))); do
    set -- ${TARGET[$idx]}
    var_GOOS=$1
    var_GOARCH=$2
    
    core_binary="../lib/exec/perfmonger-core_${var_GOOS}_${var_GOARCH}"
    
    if [ -f "$core_binary" ]; then
        for subcmd in recorder player viewer summarizer plot-formatter; do
            wrapper_name="../lib/exec/perfmonger-${subcmd}_${var_GOOS}_${var_GOARCH}"
            
            # Create a symlink to the core binary
            ln -sf "perfmonger-core_${var_GOOS}_${var_GOARCH}" "$wrapper_name"
        done
    fi
done
