#!/bin/bash

cd $(cd $(dirname $0); pwd)

source ../00_LOAD_GO_DEVENV.sh

if [[ $1 = "-" ]]; then
    # do self build
    case `uname -s` in
        (Linux)
            os="linux"
            ;;
        (Darwin)
            os="darwin"
            ;;
        (*)
            os=""
            ;;
    esac
    case `uname -m` in
        (x86_64|amd64)
            arch="amd64"
            ;;
        (*)
            arch=""
            ;;
    esac

    TARGET=("${os} ${arch}")
else
    # cross build
    TARGET=("linux amd64")
fi

set -e

GO_DEPS=$(ls internal/perfmonger/*.go)

makefile=`mktemp`

cat <<EOF > $makefile
# DO NOT EDIT MANUALLY
# generated by build.sh

GO_DEPS := $(echo ${GO_DEPS})

GOPATH := ${GOPATH}
GOROOT := ${GOROOT}

.PHONY: all build clean

all: build

EOF

TARGETS=()

for idx in $(seq 0 $((${#TARGET[@]}-1))); do
    set -- ${TARGET[$idx]}
    export var_GOOS=$1
    export var_GOARCH=$2

    for subcmd in recorder player viewer summarizer plot-formatter; do
        TARGETS+=(../lib/exec/perfmonger-${subcmd}_${var_GOOS}_${var_GOARCH})

        cat <<EOF >> $makefile

../lib/exec/perfmonger-${subcmd}_${var_GOOS}_${var_GOARCH}: cmd/perfmonger-${subcmd}/perfmonger-${subcmd}.go \$(GO_DEPS)
	cd cmd/perfmonger-${subcmd} && go build -o ../../\$@ perfmonger-$subcmd.go

EOF
    done

    # go build -o ../lib/exec/perfmonger-recorder_${var_GOOS}_${var_GOARCH} \
    #     perfmonger-recorder.go &
    # go build -o ../lib/exec/perfmonger-player_${var_GOOS}_${var_GOARCH} \
    #     perfmonger-player.go &
    # go build -o ../lib/exec/perfmonger-summarizer_${var_GOOS}_${var_GOARCH} \
    #    perfmonger-summarizer.go &

done

cat <<EOF >> $makefile

build: ${TARGETS[*]}

clean:
	rm -f ${TARGETS[*]}

EOF

mv $makefile ./Makefile

make
