# This file is automatically generated by Autoconf: 2014-06-23 19:42:25

module PerfMonger
  ROOTDIR = File.expand_path("../../..", __FILE__)
  DATAROOTDIR = File.expand_path("../../../data", __FILE__)
end
